### ISSUE TITLE
Use native percentage()

### ISSUE THREAD

**Issue by KittyGiraudel** [jclem/flexgrid#1]
Hey,

Instead of doing:

```
$column-pct-width:    ($column-width / $container-width) * 100%;
```

I guess you could make use of the native percentage() Sass function: http://sass-lang.com/docs/yardoc/Sass/Script/Functions.html#percentage-instance_method.

```
$column-pct-width:    percentage($column-width / $container-width);
```

Cheers.

**Comment by jclem** [comment]
@HugoGiraudel I don't really maintain this project anymore, but pull request!
